version: "3.9"
services:
  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - ./docker/services/promtail/config.yml:/etc/promtail/config.yml
      - ./logs:/var/log
    command: -config.file=/etc/promtail/config.yml -config.expand-env
    restart: unless-stopped
    environment:
      - HOST_HOSTNAME=${HOSTNAME}
