name: E2E Test Linux CLI e2e

on:
  push:
    branches: [ main, framework ]

jobs:
  e2e-test-linux-e2e:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python 3.10"
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: "Add conda to system path"
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: "Install requirements"
        run: |
          pip install -r requirements.txt
      - name: "Setup env"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HELICONE_API_KEY: ${{ secrets.HELICONE_API_KEY }}
        run: |
          export OPENAI_API_KEY="$OPENAI_API_KEY"
          # export HELICONE_API_KEY="$HELICONE_API_KEY"
      - name: "Start Copilot"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          nohup python example.py &> logs.log &
          sleep 30
      - name: "Test Backend"
        run: |
          PYTHONPATH=. python tests/e2e/test_backend.py
