name: E2E Test MacOS CLI

on:
  push:
    branches: [ main, reconfigure-ci ]

jobs:
  e2e-test-macos-cli:
    runs-on: macOS
    strategy:
      max-parallel: 1

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python"
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python --version
          pip install --upgrade pip
          pip --version
      - name: "Clean up Docker"
        run: |
          docker stop $(docker ps -aq) 2>/dev/null || true
          docker rm $(docker ps -aq) 2>/dev/null || true
      - name: "Install SDK"
        run: |
          source venv/bin/activate
          pip install -e .
          opencopilot --help
      - name: "Create Copilot"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HELICONE_API_KEY: ${{ secrets.HELICONE_API_KEY }}
        run: |
          source venv/bin/activate
          printf "1\n$OPENAI_API_KEY\ny\nCopilotName\n" | opencopilot create
          echo "HELICONE_API_KEY = \"$HELICONE_API_KEY\"" >> backend/.env
      - name: "Start Copilot"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          source venv/bin/activate
          opencopilot start
      - name: "Test backend"
        run: |
          source venv/bin/activate
          cd backend && PYTHONPATH=. python tests/e2e/test_backend.py
      - name: "Stop Copilot"
        run: |
          source venv/bin/activate
          opencopilot stop
      - name: "Test is copilot stopped"
        run: |
          num_containers=$(docker ps -q | wc -l)
          echo "num_containers: $num_containers"
          if [ $num_containers -gt 0 ]; then exit 1; fi;