name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    name: Check for linting errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Black
        run: |
          pip install black
          black --check .
      - name: Lint Ruff
        run: |
          pip install ruff
          ruff check .