name: Security Check

on: [pull_request]

jobs:
  security-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "TruffleHog OSS"
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified